name: CI

on:
  push:
    branches:
      - hspice
  pull_request:
    branches:
      - hspice
  workflow_dispatch:


jobs:

  Run:
    strategy:
      fail-fast: false
      matrix:
        library:
          - all
    env:
      STD_CELL_LIBRARY: ${{ matrix.library }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Build
      run: |
        bash .github/build.sh

    - name: Capture
      if: ${{ always() }}
      run: |
        bash .github/capture.sh

    - name: Upload
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.library }}
        path: ${{ github.workspace }}/output/**
    - name: Release
      uses: softprops/action-gh-release@v1
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.workspace }}/output/hspice-model.tar.bz2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
