name: CI

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:

  Run:
    strategy:
      fail-fast: false
      matrix:
        library:
          - sky130_fd_sc_hd
          - sky130_fd_sc_hdll
          - sky130_fd_sc_hs
          - sky130_fd_sc_ms
          - sky130_fd_sc_ls
          - sky130_fd_sc_hvl
          - all
    env:
      STD_CELL_LIBRARY: ${{ matrix.library }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Build
      run: |
        bash .github/build.sh

    - name: Test
      run: |
        bash .github/test.sh

    - name: Capture
      if: ${{ always() }}
      run: |
        bash .github/capture.sh

    - name: Upload
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.library }}
        path: ${{ github.workspace }}/output/**
